package yio.tro.opacha.menu.scenes;

import yio.tro.opacha.game.touch_modes.SceneEditSinglePlanet;
import yio.tro.opacha.menu.scenes.editor.*;
import yio.tro.opacha.menu.scenes.gameplay.*;
import yio.tro.opacha.menu.scenes.info.SceneDebugData;
import yio.tro.opacha.menu.scenes.info.help.*;
import yio.tro.opacha.menu.scenes.info.SceneAboutGame;
import yio.tro.opacha.menu.scenes.info.SceneSpecialThanks;
import yio.tro.opacha.menu.scenes.options.SceneLanguages;
import yio.tro.opacha.menu.scenes.options.SceneSettingsMenu;
import yio.tro.opacha.menu.scenes.tutorial.*;

public class Scenes {

    public static SceneMainMenu mainMenu;
    public static SceneAboutGame aboutMenu;
    public static SceneChooseGameMode chooseGameMode;
    public static SceneGameOverlay gameOverlay;
    public static ScenePauseMenu pauseMenu;
    public static SceneNotification notification;
    public static SceneExceptionReport exceptionReport;
    public static SceneSettingsMenu settingsMenu;
    public static SceneHelpMenu helpMenu;
    public static SceneSpecialThanks specialThanks;
    public static SceneLanguages languages;
    public static SceneCatchedException catchedException;
    public static SceneLoadingScreen loadingScreen;
    public static SceneSecretScreen secretScreen;
    public static SceneSkirmishMenu skirmishMenu;
    public static SceneConfirmRestart confirmRestart;
    public static SceneKeyboard keyboard;
    public static SceneCampaign campaign;
    public static SceneDebugPanel debugPanel;
    public static SceneSpeedControls speedControls;
    public static SceneSelectionOverlay selectionOverlay;
    public static SceneMatchResults matchResults;
    public static SceneOnCampaignLevelCompleted onCampaignLevelCompleted;
    public static SceneTutorialBegin tutorialBegin;
    public static SceneTutorialYourPlanets tutorialYourPlanets;
    public static SceneTutorialBasicControls tutorialBasicControls;
    public static SceneTutorialShields tutorialShields;
    public static SceneTutorialUpgradesOne tutorialUpgradesOne;
    public static SceneTutorialUpgradesTwo tutorialUpgradesTwo;
    public static SceneTutorialAutoTarget tutorialAutoTarget;
    public static SceneTutorialDeselect tutorialDeselect;
    public static SceneTutorialHalvedSelection tutorialHalvedSelection;
    public static SceneTutorialEnd tutorialEnd;
    public static SceneReward reward;
    public static SceneEndSpectate endSpectate;
    public static SceneEditorLobby editorLobby;
    public static SceneEditorOverlay editorOverlay;
    public static SceneEditorOptionsPanel editorOptionsPanel;
    public static SceneEditorPauseMenu editorPauseMenu;
    public static SceneResetTouchMode resetTouchMode;
    public static SceneEditSinglePlanet editSinglePlanet;
    public static SceneEditorSave editorSave;
    public static SceneEditorLoad editorLoad;
    public static SceneEditorPrepareToLaunch editorPrepareToLaunch;
    public static SceneEditorSlotContextActions editorSlotContextActions;
    public static SceneVelocityControls velocityControls;
    public static SceneQuickVelocityTutorial quickVelocityTutorial;
    public static SceneLockCamera lockCamera;
    public static SceneForefinger forefinger;
    public static SceneGlobalMessage globalMessage;
    public static SceneAttraction attraction;
    public static SceneCalendar calendar;
    public static SceneDebugData debugData;
    public static SceneMyGamesButton myGamesButton;
    public static SceneMyGamesArticle myGamesArticle;


    public static void createAllScenes() {
        mainMenu = new SceneMainMenu();
        aboutMenu = new SceneAboutGame();
        chooseGameMode = new SceneChooseGameMode();
        gameOverlay = new SceneGameOverlay();
        pauseMenu = new ScenePauseMenu();
        notification = new SceneNotification();
        exceptionReport = new SceneExceptionReport();
        settingsMenu = new SceneSettingsMenu();
        helpMenu = new SceneHelpMenu();
        specialThanks = new SceneSpecialThanks();
        languages = new SceneLanguages();
        catchedException = new SceneCatchedException();
        loadingScreen = new SceneLoadingScreen();
        secretScreen = new SceneSecretScreen();
        skirmishMenu = new SceneSkirmishMenu();
        confirmRestart = new SceneConfirmRestart();
        keyboard = new SceneKeyboard();
        campaign = new SceneCampaign();
        debugPanel = new SceneDebugPanel();
        speedControls = new SceneSpeedControls();
        selectionOverlay = new SceneSelectionOverlay();
        matchResults = new SceneMatchResults();
        onCampaignLevelCompleted = new SceneOnCampaignLevelCompleted();
        tutorialBegin = new SceneTutorialBegin();
        tutorialYourPlanets = new SceneTutorialYourPlanets();
        tutorialBasicControls = new SceneTutorialBasicControls();
        tutorialShields = new SceneTutorialShields();
        tutorialUpgradesOne = new SceneTutorialUpgradesOne();
        tutorialUpgradesTwo = new SceneTutorialUpgradesTwo();
        tutorialAutoTarget = new SceneTutorialAutoTarget();
        tutorialDeselect = new SceneTutorialDeselect();
        tutorialHalvedSelection = new SceneTutorialHalvedSelection();
        tutorialEnd = new SceneTutorialEnd();
        reward = new SceneReward();
        endSpectate = new SceneEndSpectate();
        editorLobby = new SceneEditorLobby();
        editorOverlay = new SceneEditorOverlay();
        editorOptionsPanel = new SceneEditorOptionsPanel();
        editorPauseMenu = new SceneEditorPauseMenu();
        resetTouchMode = new SceneResetTouchMode();
        editSinglePlanet = new SceneEditSinglePlanet();
        editorSave = new SceneEditorSave();
        editorLoad = new SceneEditorLoad();
        editorPrepareToLaunch = new SceneEditorPrepareToLaunch();
        editorSlotContextActions = new SceneEditorSlotContextActions();
        velocityControls = new SceneVelocityControls();
        quickVelocityTutorial = new SceneQuickVelocityTutorial();
        lockCamera = new SceneLockCamera();
        forefinger = new SceneForefinger();
        globalMessage = new SceneGlobalMessage();
        attraction = new SceneAttraction();
        calendar = new SceneCalendar();
        debugData = new SceneDebugData();
        myGamesButton = new SceneMyGamesButton();
        myGamesArticle = new SceneMyGamesArticle();
    }
}
